name: VOrchestrator Benchmarks

on:
  # Run benchmarks manually from the Actions tab
  workflow_dispatch:
  
  # Run benchmarks on new releases
  release:
    types: [published]
  
  # Optionally run on a schedule (weekly)
  schedule:
    - cron: '0 0 * * 0' # Once a week on Sunday

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup V
      uses: vlang/setup-v@v1
      with:
        check-latest: true
    
    - name: Install dependencies
      run: v install
      
    - name: Build VOrchestrator with optimizations
      run: v -prod .
    
    - name: Run basic performance test
      run: |
        echo "## VOrchestrator Performance Metrics" > benchmark-report.md
        echo "" >> benchmark-report.md
        
        # Measure binary size
        if [ -f "./VOrchestrator" ]; then
          SIZE=$(wc -c < "./VOrchestrator")
          SIZE_KB=$((SIZE / 1024))
          echo "- **Binary Size:** $SIZE_KB KB" >> benchmark-report.md
          echo "Binary Size: $SIZE_KB KB"
        else
          echo "- **Binary Size:** Not available (build failed)" >> benchmark-report.md
          echo "Binary not found!"
        fi
        
        # Measure startup time
        time ./VOrchestrator || echo "Command execution failed"
        
        echo "" >> benchmark-report.md
        echo "Benchmark completed at $(date)" >> benchmark-report.md
      shell: bash
    
    - name: Add benchmark summary
      run: |
        echo "### VOrchestrator Benchmark Results" >> $GITHUB_STEP_SUMMARY
        cat benchmark-report.md >> $GITHUB_STEP_SUMMARY
      shell: bash
