name: VOrchestrator Benchmarks

on:
  # Run benchmarks manually from the Actions tab
  workflow_dispatch:
  
  # Run benchmarks on new releases
  release:
    types: [published]
  
  # Optionally run on a schedule (weekly)
  schedule:
    - cron: '0 0 * * 0' # Once a week on Sunday

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup V
      uses: vlang/setup-v@v1
      with:
        check-latest: true
    
    - name: Install dependencies
      run: v install
      
    - name: Build VOrchestrator with optimizations
      run: v -prod .
    
    - name: Run basic performance test
      run: |
        echo "VOrchestrator Basic Performance Test" > benchmark_results.txt
        echo "======================================" >> benchmark_results.txt
        echo "" >> benchmark_results.txt
        
        # Measure binary size
        if [ -f "./VOrchestrator" ]; then
          SIZE=$(stat -c %s "./VOrchestrator")
          SIZE_KB=$((SIZE / 1024))
          echo "Binary Size: $SIZE_KB KB" >> benchmark_results.txt
          echo "Binary Size: $SIZE_KB KB"
        else
          echo "Binary not found!" >> benchmark_results.txt
          echo "Binary not found!"
        fi
        
        # Measure startup time
        START=$(date +%s%N)
        ./VOrchestrator
        END=$(date +%s%N)
        DURATION=$((($END - $START)/1000000))
        echo "Startup Time: $DURATION ms" >> benchmark_results.txt
        echo "Startup Time: $DURATION ms"
        
        # Report test completion
        echo "" >> benchmark_results.txt
        echo "Test completed at: $(date)" >> benchmark_results.txt
        echo "Test completed successfully!"
      shell: bash
        
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmark_results.txt
