name: Create Release

on:
  push:
    tags:
      - 'v*' # Run when tag is pushed matching pattern v*, like v0.1.0

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true
      
      - name: Build for Linux
        run: v -prod -o VOrchestrator-linux .
      
      - name: Generate release notes
        run: |
          echo "VOrchestrator Release" > RELEASE_INFO.md
          echo "=====================" >> RELEASE_INFO.md
          echo "" >> RELEASE_INFO.md
          cat RELEASE_NOTES.md >> RELEASE_INFO.md
          echo "" >> RELEASE_INFO.md
          echo "## Changelog" >> RELEASE_INFO.md
          echo "" >> RELEASE_INFO.md
          cat CHANGELOG.md >> RELEASE_INFO.md
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_INFO.md
          files: |
            VOrchestrator-linux
          draft: false
          prerelease: false
  
  build-macos:
    needs: build-and-release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true
      
      - name: Build for macOS
        run: v -prod -o VOrchestrator-macos .
      
      - name: Upload macOS Binary
        uses: softprops/action-gh-release@v1
        with:
          files: VOrchestrator-macos
          draft: false
          prerelease: false
